### ISSUE TITLE
Exception levée

### ISSUE THREAD

**Issue by eMachabeeUdeS** [RobuckUS/APP7-S2#11]
Exception levée à 0x00007FF8DE0A668F (Qt5Widgetsd.dll) dans ConnectFour.exe : 0xC0000005 : Violation d'accès lors de la lecture de l'emplacement 0xFFFFFFFFFFFFFFFF.

Lors de l'exécution et l'empilage de jetons, le jeu crash et l'erreur suivante est affichée:
![image](https://user-images.githubusercontent.com/54988665/79289815-5ab28880-7e98-11ea-9387-9e278c1dcc91.png)
Ligne 69 de TableauJeu.cpp

**Comment by mdaoustUdeS** [comment]
Est-ce que ça arrive lorsqu'on rajoute un jeton de plus apres avoir gagné?

**Comment by eMachabeeUdeS** [comment]
![image](https://user-images.githubusercontent.com/54988665/79290008-ef1ceb00-7e98-11ea-8929-5205f8e53340.png)
Voici ce qui est affiché

**Comment by eMachabeeUdeS** [comment]
> 
> 
> Est-ce que ça arrive lorsqu'on rajoute un jeton de plus apres avoir gagné?

Je ne sais pas, je n'ai que pilé des jetons vers le haut et ça a causé ce problème.

**Comment by mdaoustUdeS** [comment]
**Solution proposé**
Créer un booléen isPlaying à true au début et à fasle dans setWinner()

Activate keyboard when setWinner() == true
